selected-player = "mpvc"

[player-configuration.audacious.shell-commands]
play = "audacious --play"
play-toggle = "audacious --play-pause"
previous = "audacious --rew"
next = "audacious --fwd"
stop = "audacious --stop"
spawn-server = "audacious"

[player-configuration.mpvc.shell-commands]
play = "mpvc play"
play-toggle = "mpvc toggle"
previous = "mpvc prev"
next = "mpvc next"
stop = "mpvc stop"
spawn-server = "%RUN_IN_TERMINAL% mpvc-tui -T"
