[colors.primary]
background = "#f2e5bc"
foreground = "#3c3836"

[colors.normal]
black   = "#3c3836"
red     = "#9d0006"
green   = "#79740e"
yellow  = "#b57614"
blue    = "#076678"
magenta = "#8f3f71"
cyan    = "#427b58"
white   = "#928374"

[colors.bright]
black   = "#002b36"
red     = "#af3a03"
green   = "#586e75"
yellow  = "#657b83"
blue    = "#839496"
magenta = "#6c71c4"
cyan    = "#93a1a1"
white   = "#fdf6e3"
