[nim]

main-program = "wenzels-keyboard"
main-source = "./wenzels_keyboard.nim"

build-arguments = [
	"--mm:atomicArc",
]

nix-build-extra-arguments = [
	"-d:release",
	"--nimcache:nimcache",
]

lint-arguments = [
	"--colors:off",
	"--styleCheck:error",
	"--hintAsError:XDeclaredButNotUsed:on",
]
