[nim]

main-program = "pointer-setup"
main-source = "./pointer_setup.nim"

build-arguments = [
	"--mm:atomicArc",
]

nix-build-extra-arguments = [
	"-d:release",
	"--nimcache:nimcache",
]

lint-arguments = [
	"--colors:off",
	"--styleCheck:error",
	"--hintAsError:XDeclaredButNotUsed:on",
]
